POST http://127.0.0.1:8000/api/devices/
Content-Type: application/json
Authorization: Bearer supersecret

{
    "name": "sensor 9",
    "location_id": 3
}

###
POST http://127.0.0.1:8000/api/devices/sensor-1/set-location/
Content-Type: application/json

{
    "location_id":3
}

### 

POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}